### ISSUE TITLE
PCD_Version returns 0

### ISSUE THREAD

**Issue by Valraox** [anuragmandal/ESPIDF-INTERFACE-MFRC522#1]
I'm trying to read from RFID and PCD_Version function is returning 0 value so the device is rebooting all time. I have checked the pin connections several times as defined in MFRC522.h and didn't work.

**Comment by anuragmandal** [comment]
Yaa Valraox thank you for sharing issues. I will check that and I will get back to you asap. Please make sure PIN_NUM_CS(GPIO -22) should be connected with SDA line of MFRC522. Can you share the debug messages and connection which you had made as screenshots?

**Comment by Valraox** [comment]
Here is the output from the console:
![MFRC522](https://user-images.githubusercontent.com/23363783/64938754-34bff980-d85f-11e9-853a-e4d84e382331.png)

**Comment by Valraox** [comment]
Well, we have checked connections with GPIO extension on board and now it's getting version number, but the program enter on loop and is not reading the RFID cards. This is the console output (From there is on "Allocate RX buffer for DMA":
![MFRC522-2](https://user-images.githubusercontent.com/23363783/64941981-3fcb5780-d868-11e9-8b10-71158b13dac0.png)

Later is putting
![MFRC522-3](https://user-images.githubusercontent.com/23363783/64942281-f3cce280-d868-11e9-93ed-0409f8c13487.png)

**Comment by Valraox** [comment]
I'm testing to determinate where it's the problem. In the call to function PICC_RequestA on function PICC_IsNewCardPresent is where buffer infinite loops but I don't know why.

**Comment by anuragmandal** [comment]
Today I will check this one but I am using esp idf v3.0 to test and it able
to detect card and uid of the card also.i have to check with your idf
version also.

**Comment by Valraox** [comment]
The version of esp-idf repository I'm using to compile is v4.0-dev-621-g81ca1c013.
I tried to compile changing the sources of spi_master.c and spi_master.h from other repository installed by esp-idf for Windows which is on version v3.2.2 with same result.

**Comment by anuragmandal** [comment]
I have to download esp idf v3.1.3 then I will check with this one and let
you know asap. Currently with esp idf 3.0 it's working fine I checked now.

**Comment by Valraox** [comment]
Well, now with esp-idf v3.0 is not in infinite loop about buffer for DMA, but isn't reading card, this is the output:
![MFRC522-4](https://user-images.githubusercontent.com/23363783/65056150-a89df700-d970-11e9-87d4-b25dcede11cb.png)
Note: I added printf with "LOOP INTIALIZATION"

**Comment by anuragmandal** [comment]
Try with disabling the watchdog in sdkconfig file. It will better if you show your connection pins with module. Below is the debug message that what i am getting. 
![Capture7](https://user-images.githubusercontent.com/54491744/65063789-92a62b80-d99c-11e9-87b3-be6b03b569a2.JPG)

**Comment by Valraox** [comment]
I disabled "Interrupt watchdog" and "Initialize Task Watchdog Timer on startup" on menuconfig but it isn't reading the card (I'm using the card provided with the module RC522). I'm receiving un the result from PICC_IsNewCardPresent function 3 value, I see in the code is STATUS_TIMEOUT. I put a printf to show the result:
![MFRC522-5](https://user-images.githubusercontent.com/23363783/65123652-01fb3a00-d9f4-11e9-9523-90416bb2fc6e.png)
Note: I'm using default GPIO in the code, the conections from module is:
-SDA -> GPIO 22 (Extension pin 22)
-SCK -> GPIO 19 (Extension pin 20)
-MOSI -> GPIO 23 (Extension pin 23)
-MISO -> GPIO 25 (Extension pin 24)
-IRQ -> Not connected
-GND -> Extension pin 35
-RST -> GPIO 14 (Extension pin 15)
-3.3V -> Extension pin 37
I attached extension pin schema:
![imagen](https://user-images.githubusercontent.com/23363783/65130453-c06f8c80-d9fd-11e9-901b-6168de85d98b.png)

**Comment by anuragmandal** [comment]
In function PCD_CommunicateWithPICC()
Add debug statement as below :-
for (i = 20000; i > 0; i--) { n = PCD_ReadRegister(spi,ComIrqReg); 
 if (n & waitIRq) {
/*Add debug message here */
printf ("GOT INTERRUPT SIGNAL\n");
break; 
} 
if (n & 0x01)
 { 
   return STATUS_TIMEOUT;
 } 
}
So after adding load the code and check by placing card near to reader and check  in debug will it able to print the message
"Got interrupt signal" or not. If not means it not able to read irq register. 


As I have tested the code with below link module its working
https://docs.zerynth.com/latest/official/board.zerynth.doit_esp32/docs/index.html
Which module or kit are you using ?
So in your module the default pins which I am using might it connected with somewhere else also which can cause problem in transmitting and receiving data. So you can test by assigning other pins.

**Comment by Valraox** [comment]
Finally it works!! It was the pins on the board, in the datasheet I have didn't say anything of GPIOS usage, I found other document where was the correct ones for SPI. I'm using a ESP32-EVB_rev_d 
https://riot-os.org/api/group__boards__esp32__olimex-esp32-evb.html#pinout
When I was testing other GPIOS I should have used a wrong reset pin. Actually I'm using:
#define PIN_NUM_MISO 2
#define PIN_NUM_MOSI 15
#define PIN_NUM_CLK  14
#define PIN_NUM_CS   17

#define PIN_NUM_RST  4
![MFRC522-6](https://user-images.githubusercontent.com/23363783/65225643-ccbf1c80-dac5-11e9-99f0-50f16bcaa00e.png)
Thanks a lot for all the help!!

**Comment by anuragmandal** [comment]
Ok great .
Always welcome. Have a great day. Any help you can ping me.

**Comment by Mauricio-Alencar** [comment]
Good afternoon guys, will this lib have portability to version v4.0 of the SDK-IDF? Using version v4 I have the same problem as the friend in the dynamic allocation of DMA, however, I did not want to have to regress the version on my computer because of other projects ...

**Comment by Valraox** [comment]
Good afternoon, I finally used v4.0 from SDK-IDF in the project because other functionalities not working on v3.0 but I copy the libraries of SPI from v3 and pasted in the v4.0.
If you don't need new v4.0 SPI library or work with v3 you can do that.
The C files are on 'components/driver' folder:
-spi_common.c
-spi_master.c
-spi_slave.c
And the headers on 'components/driver/include/driver'
-spi_common.h
-spi_master.h
-spi_slave.h

**Comment by Mauricio-Alencar** [comment]
Thank u @Valraox , i go to test your implementations and i will bring feedback!

**Comment by anuragmandal** [comment]
Resolved
