### ISSUE TITLE
watchdog trigger

### ISSUE THREAD

**Issue by ankit-thealchemist** [anuragmandal/ESPIDF-INTERFACE-MFRC522#2]
Hello, 

Thanks for making this library, which is working fine on esp-idf v4.4.  The only short coming I found is the watchdog trigger. surely We I can understand that, I can disable that, but I am more interested to know the cause of the problem. 
I am also interested to make this library official library of esp-idf for RC522. But for this I need your help.

**Comment by anuragmandal** [comment]
Can you send me the console logs for better understanding.

**Comment by yka8247** [comment]
rst:0x1 (POWERON_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6844
ho 0 tail 12 room 4
load:0x40078000,len:16092
load:0x40080400,len:3980
entry 0x400806a8
[0;32mI (29) boot: ESP-IDF 4.4.1 2nd stage bootloader
32mI (29) boot: compile time 16:19:25
I (29) boot: chip revision: 3
I (32) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (39) boot.esp32: SPI Speed      : 40MHz
I (44) boot.esp32: SPI Mode       : DIO
I (48) boot.esp32: SPI Flash Size : 16MB[0m
I (53) boot: Enabling RNG early entropy source...m
I (58) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (76) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  2 factory          factory app      00 00 00010000 00100000m
I (91) boot: End of partition table
I (96) boot_comm: chip revision: 3, min. application chip revision: 0[0m
I (103) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=1f320h (127776) map
[0;32mI (155) esp_image: segment 1: paddr=0002f348 vaddr=3ffb0000 size=00cd0h (  3280) load
I (157) esp_image: segment 2: paddr=00030020 vaddr=400d0020 size=9a540h (632128) mapm
[0;32mI (380) esp_image: segment 3: paddr=000ca568 vaddr=3ffb0cd0 size=02b40h ( 11072) load
I (384) esp_image: segment 4: paddr=000cd0b0 vaddr=40080000 size=16438h ( 91192) load0m
[0;32mI (421) esp_image: segment 5: paddr=000e34f0 vaddr=50000000 size=00010h (    16) load
[0;32mI (431) boot: Loaded app from partition at offset 0x10000[0m
I (432) boot: Disabling RNG early entropy source...[0m
I (443) cpu_start: Pro cpu up.
I (444) cpu_start: Starting app cpu, entry point is 0x400828f0
32mI (0) cpu_start: App cpu up.
[0;32mI (458) cpu_start: Pro cpu start user code
I (458) cpu_start: cpu freq: 160000000
I (458) cpu_start: Application information:
I (462) cpu_start: Project name:     galleon
I (467) cpu_start: App version:      0.1.6-11-g6a7f407-dirty
I (474) cpu_start: Compile time:     Aug 15 2022 16:16:15
I (480) cpu_start: ELF file SHA256:  4f1ca92296a0829a...
I (486) cpu_start: ESP-IDF:          4.4.1
I (491) heap_init: Initializing. RAM available for dynamic allocation:
I (498) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
[0;32mI (504) heap_init: At 3FFB7758 len 000288A8 (162 KiB): DRAM
I (510) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (516) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (523) heap_init: At 40096438 len 00009BC8 (38 KiB): IRAM
I (530) spi_flash: detected chip: generic
I (534) spi_flash: flash io: dio0m
I (539) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
[0;32mI (708) MAIN: Initialize QO IoT Device
I (708) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 
I (708) gpio: GPIO[25]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 
I (718) gpio: GPIO[27]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 
I (728) gpio: GPIO[26]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:3 
I (738) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:3 
I (748) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:3 
I (758) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:3 
I (768) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:3 
Version:92
MFRC522 Version 2 detected.
I (818) wifi:wifi driver task: 3ffc4ce4, prio:23, stack:6656, core=0
I (818) system_api: Base MAC address is not set
I (818) system_api: read default base MAC address from EFUSE
I (828) wifi:wifi firmware version: 63017e0
I (828) wifi:wifi certification version: v7.0
I (828) wifi:config NVS flash: enabled
I (838) wifi:config nano formating: disabled
I (838) wifi:Init data frame dynamic rx buffer num: 32
I (838) wifi:Init management frame dynamic rx buffer num: 32
I (848) wifi:Init management short buffer num: 32
I (848) wifi:Init dynamic tx buffer num: 32
I (858) wifi:Init static rx buffer size: 1600
I (858) wifi:Init static rx buffer num: 10
I (868) wifi:Init dynamic rx buffer num: 32
I (868) wifi_init: rx ba win: 6
I (868) wifi_init: tcpip mbox: 32
I (878) wifi_init: udp mbox: 6
I (878) wifi_init: tcp mbox: 6
I (878) wifi_init: tcp tx win: 5744
2mI (888) wifi_init: tcp rx win: 5744
I (888) wifi_init: tcp mss: 1440
I (898) wifi_init: WiFi IRAM OP enabled
I (898) wifi_init: WiFi RX IRAM OP enabledm
I (908) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (1018) wifi:mode : sta (c0:49:ef:0a:76:34)
I (1018) wifi:enable tsf
I (1028) wifi:set country: cc=US schan=1 nchan=11 policy=0

I (1028) connect: event_handler: WIFI_EVENT:START[0m
Antenna turned on.
Initialization successful.
I (1638) wifi:new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
I (1638) wifi:state: init -> auth (b0)
I (2978) wifi:state: auth -> assoc (0)
E (2988) wifi:Association refused temporarily, comeback time 1499 mSec
I (4488) wifi:state: assoc -> assoc (0)
E (4498) wifi:Association refused temporarily, comeback time 1499 mSec
I (5498) wifi:state: assoc -> init (9a0)
I (5498) wifi:new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
I (5498) connect: event_handler: WIFI_EVENT:DISCONNECTED
[0;31mE (5908) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (5908) task_wdt:  - IDLE (CPU 0)
E (5908) task_wdt: Tasks currently running:
E (5908) task_wdt: CPU 0: rfid_task
E (5908) task_wdt: CPU 1: IDLE
E (5908) task_wdt: Print CPU 0 (current core) backtrace


Backtrace:0x4015B5A6:0x3FFB09200x40083AFD:0x3FFB0950 0x40082501:0x3FFC07C0 0x4008203D:0x3FFC07E0 0x400DA57F:0x3FFC0800 0x400DA2EB:0x3FFC0820 0x400DA34F:0x3FFC0860 0x400D3912:0x3FFC0890 0x400D3C18:0x3FFC08E0 0x400D3D11:0x3FFC0910 0x400D3D65:0x3FFC0960 0x400D37EB:0x3FFC0990 

E (5908) task_wdt: Print CPU 1 backtrace


Backtrace:0x4008828D:0x3FFB0F300x40083AFD:0x3FFB0F50 0x4000BFED:0x3FFBB580 0x4008D22A:0x3FFBB590 0x4015B8B3:0x3FFBB5B0 0x4015B8BF:0x3FFBB5D0 0x400DCEB6:0x3FFBB5F0 0x4008B4B3:0x3FFBB610 

[0;32mI (6828) connect: event_handler: WIFI_EVENT:DISCONNECTED[0m
I (6838) wifi:new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
I (6838) wifi:state: init -> auth (b0)
I (8288) wifi:state: auth -> assoc (0)
I (8298) wifi:state: assoc -> run (10)
I (8318) wifi:connected with YK_S21, aid = 1, channel 6, BW20, bssid = 26:61:e4:90:a5:76
I (8318) wifi:security: WPA3-SAE, phy: bgn, rssi: -66
I (8328) wifi:pm start, type: 1

I (8328) connect: event_handler: WIFI_EVENT:CONNECTED
W (8338) wifi:<ba-add>idx:0 (ifx:0, 26:61:e4:90:a5:76), tid:0, ssn:0, winSize:64
I (8688) wifi:AP's beacon interval = 102400 us, DTIM period = 2
[0;32mI (9308) esp_netif_handlers: sta ip: 192.168.101.172, mask: 255.255.255.0, gw: 192.168.101.183
I (9308) connect: event_handler: IP_EVENT:ISSUED
I (9308) connect: got ip:192.168.101.172
E (9328) wifi:CCMP replay detected: A1=c0:49:ef:0a:76:34 A2=26:61:e4:90:a5:76 PN=5, RSC=5 seq=63152
[0;32mI (9418) REST-API: HTTP POST Status = 200, content_length = -1
I (9428) REST-API: HTTP_EVENT_DISCONNECTED
[0;32mI (9498) REST-API: HTTP GET Status = 200, content_length = -1
I (9498) UI: Get Request updates LCD
2mI (9498) REST-API: HTTP_EVENT_DISCONNECTED
[0;31mE (10908) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (10908) task_wdt:  - IDLE (CPU 0)
E (10908) task_wdt: Tasks currently running:
E (10908) task_wdt: CPU 0: rfid_task
E (10908) task_wdt: CPU 1: IDLE
1mE (10908) task_wdt: Print CPU 0 (current core) backtrace


Backtrace:0x4015B5A6:0x3FFB09200x40083AFD:0x3FFB0950 0x4000BFED:0x3FFC0790 0x4008D22A:0x3FFC07A0 0x400824FF:0x3FFC07C0 0x4008203D:0x3FFC07E0 0x400DA57F:0x3FFC0800 0x400DA2EB:0x3FFC0820 0x400DA34F:0x3FFC0860 0x400D3912:0x3FFC0890 0x400D3C18:0x3FFC08E0 0x400D3D11:0x3FFC0910 0x400D3D65:0x3FFC0960 0x400D37EB:0x3FFC0990 

E (10908) task_wdt: Print CPU 1 backtrace


Backtrace:0x4008828D:0x3FFB0F300x40083AFD:0x3FFB0F50 0x4000BFED:0x3FFBB580 0x4008D22A:0x3FFBB590 0x4015B8B3:0x3FFBB5B0 0x4015B8BF:0x3FFBB5D0 0x400DCEB6:0x3FFBB5F0 0x4008B4B3:0x3FFBB610 

[0;31mE (15908) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (15908) task_wdt:  - IDLE (CPU 0)
E (15908) task_wdt: Tasks currently running:
E (15908) task_wdt: CPU 0: rfid_task
E (15908) task_wdt: CPU 1: IDLE
1mE (15908) task_wdt: Print CPU 0 (current core) backtrace


Backtrace:0x4015B5A6:0x3FFB09200x40083AFD:0x3FFB0950 0x4000BFED:0x3FFC07C0 0x4008D22A:0x3FFC07D0 0x400824FF:0x3FFC07F0 0x4008203D:0x3FFC0810 0x400DA57F:0x3FFC0830 0x400DA2EB:0x3FFC0850 0x400D3842:0x3FFC0890 0x400D3A09:0x3FFC08C0 0x400D3C0A:0x3FFC08E0 0x400D3D11:0x3FFC0910 0x400D3D65:0x3FFC0960 0x400D37EB:0x3FFC0990 

E (15908) task_wdt: Print CPU 1 backtrace

**Comment by yka8247** [comment]
[0;31mE (135988) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (135988) task_wdt:  - IDLE (CPU 1)
E (135988) task_wdt: Tasks currently running:
E (135988) task_wdt: CPU 0: IDLE
E (135988) task_wdt: CPU 1: rfid_task
[0;31mE (135988) task_wdt: Print CPU 0 (current core) backtrace[0m


Backtrace:0x4015B5A6:0x3FFB09200x40083AFD:0x3FFB0950 0x40167373:0x3FFBAB70 0x400DCEC5:0x3FFBAB90 0x4008B4B3:0x3FFBABB0 

E (135988) task_wdt: Print CPU 1 backtrace


Backtrace:0x4008828D:0x3FFB0F300x40083AFD:0x3FFB0F50 0x4000BFED:0x3FFC0790 0x4008D22A:0x3FFC07A0 0x400824FF:0x3FFC07C0 0x4008203D:0x3FFC07E0 0x400DA57F:0x3FFC0800 0x400DA2EB:0x3FFC0820 0x400DA34F:0x3FFC0860 0x400D392F:0x3FFC0890 0x400D3C18:0x3FFC08E0 0x400D3D11:0x3FFC0910 0x400D3D65:0x3FFC0960 0x400D37EB:0x3FFC0990 

*****************CARD PRESENT*****************
Card UID: c3 d0 22 98
Card SAK:  08
PICC type: MIFARE 1KB

Sector Block   0  1  2  3   4  5  6  7   8  9 10 11  12 13 14 15  AccessBits
   15     63  PCD_Authenticate() failed: Timeout in communication.
   14     59  PCD_Authenticate() failed: Timeout in communication.
   13     55  PCD_Authenticate() failed: Timeout in communication.
   12     51  PCD_Authenticate() failed: Timeout in communication.
   11     47  PCD_Authenticate() failed: Timeout in communication.
   10     43  PCD_Authenticate() failed: Timeout in communication.
     39  PCD_Authenticate() failed: Timeout in communication.
     35  PCD_Authenticate() failed: Timeout in communication.
     31  PCD_Authenticate() failed: Timeout in communication.
     27  PCD_Authenticate() failed: Timeout in communication.
     23  PCD_Authenticate() failed: Timeout in communication.
     19  PCD_Authenticate() failed: Timeout in communication.
     15  PCD_Authenticate() failed: Timeout in communication.
     11  PCD_Authenticate() failed: Timeout in communication.
      7  PCD_Authenticate() failed: Timeout in communication.
      3  PCD_Authenticate() failed: Timeout in communication.

**Comment by DheeranYuvaraj** [comment]
@anuragmandal 

When the card is not present watchdog timer is triggered. 

> MFRC522 Version 2 detected.
>Antenna turned on.
>Initialization successful.
>[1B][0;31mE (10505) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:[1B][0m
>[1B][0;31mE (10505) task_wdt:  - IDLE (CPU 0)[1B][0m
>[1B][0;31mE (10505) task_wdt: Tasks currently running:[1B][0m
>[1B][0;31mE (10505) task_wdt: CPU 0: rfid_task[1B][0m
>[1B][0;31mE (10505) task_wdt: CPU 1: IDLE[1B][0m
>[1B][0;31mE (10505) task_wdt: Print CPU 0 (current core) backtrace[1B][0m


>Backtrace:0x400D9FB7:0x3FFB0B800x4008276D:0x3FFB0BA0 0x4000BFED:0x3FFBF120 0x4008883E:0x3FFBF130 0x40086782:0x3FFBF150 0x400D8E8B:0x3FFBF190 0x400D8EBE:0x3FFBF1D0 0x400D4F66:0x3FFBF200 0x400D5289:0x3FFBF250 0x400D536D:0x3FFBF280 0x400D53A9:0x3FFBF2B0 0x400D53E2:0x3FFBF300 0x400D5416:0x3FFBF320 0x400D5EC9:0x3FFBF350 0x4008858D:0x3FFBF370 

>[1B][0;31mE (10505) task_wdt: Print CPU 1 backtrace[1B][0m


>Backtrace:0x4008496D:0x3FFB11800x4008276D:0x3FFB11A0 0x4000BFED:0x3FFB7280 0x4008883E:0x3FFB7290 0x400DA214:0x3FFB72B0 0x400DA21F:0x3FFB72E0 0x400D1B31:0x3FFB7300 0x40087026:0x3FFB7320 0x4008858D:0x3FFB7340 

*****************When CARD PRESENT (Placed above the reader)*****************

Card UID: 70 d4 4f 53

Card SAK:  08
PICC type: MIFARE 1KB

Sector Block   0  1  2  3   4  5  6  7   8  9 10 11  12 13 14 15  AccessBits

  15     63   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         62   00 00 00 00  00 04 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         61   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         60   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  14     59   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         58   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         57   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         56   00 00 00 00  00 00 00 00  00 04 00 00  00 00 00 00  [ 0 0 0 ] 
  13     55   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         54   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         53   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         52   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  12     51   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         50   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         49   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         48   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  11     47   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         46   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 04  [ 0 0 0 ] 
         45   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         44   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
  10     43   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         42   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         41   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         40   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
     39   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         38   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         37   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         36   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
     35   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         34   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         33   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         32   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
     31   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         30   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         29   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         28   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
     27   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         26   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         25   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         24   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
     23   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         22   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         21   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         20   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
     19   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         18   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         17   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         16   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
     15   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         14   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         13   00 00 00 00  00 00 00 20  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         12   00 00 00 00  00 00 00 00  00 40 00 00  00 00 00 00  [ 0 0 0 ] 
     11   00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
`

**Comment by DheeranYuvaraj** [comment]
Issue has been solved after making it as FreeRTOS code.

**Comment by anuragmandal** [comment]
Thanks, DheeranYuvraj.

Closing this issue.
